target: /mnt/c/Users/aqlan/Downloads/Consolidated Statements/
output: /mnt/c/Users/aqlan/Downloads/Consolidated Statements/Output/
accounts:
  - savings:
    regex_identifier: 222222-222222\s*ACCOUNT\s*NUMBER
    statement_config: MAYBANK_CASA_AND_MAE
    name: MAYBANK_PERSONAL_SAVER_I
    type: savings
    number: "222222222222"
    drcr: debit
  - salary:
    regex_identifier: 111111-111111\s*SELANGOR\s*ACCOUNT\s*NUMBER
    statement_config: MAYBANK_CASA_AND_MAE
    name: MAYBANK_SAVINGS_I
    type: salary
    number: "111111111111"
    drcr: debit
  - mae:
    regex_identifier: 333333333333\s*ACCOUNT\s*NUMBER\s*MAE
    statement_config: MAYBANK_CASA_AND_MAE
    name: MAYBANK_MAE
    type: wallet
    number: "333333333333"
    drcr: debit
  - maybank_cc:
    regex_identifier: PENYATA AKAUN KAD KREDIT\s*Malayan Banking Berhad \(3813-K\)
    statement_config: MAYBANK_2_CC
    name: MAYBANK_2_CC
    type: credit_card
    number: ""
    drcr: credit
statement: 
  MAYBANK_CASA_AND_MAE:
    patterns:
      starting_balance: BEGINNING BALANCE\s*([\d,]+\.\d+)
      ending_balance: ENDING BALANCE\s*:\s*([\d,]+\.\d+)
      credit_suffix: CR
      statement_date: (\d{2}\/\d{2}\/\d{2})
      statement_format: _2/01/06
      total_debit: TOTAL DEBIT\s*:\s*([\d,]+\.\d+)
      total_credit: TOTAL CREDIT\s*:\s*([\d,]+\.\d+)
      main_transaction_line: (\d{2}\/\d{2}(?:\/\d{2})?)(.+?)([\d,]*\.\d+[+-])\s([\d,]*\.\d+(DR)?)
      description_transaction_line: (^\s+\S.*)
      amount_debit_suffix: "-"
      balance_debit_suffix: DR
      date_format: "_2/1"
  MAYBANK_2_CC:
    patterns:
      credit_suffix: CR
      starting_balance: YOUR PREVIOUS STATEMENT BALANCE\s*([\d,]+\.\d+(?:CR)?)
      ending_balance: SUB TOTAL\/JUMLAH\s*([\d,]+\.\d+(?:CR)?)
      total_credit: TOTAL CREDIT THIS MONTH\s*\(JUMLAH KREDIT\)\s*([\d,]+\.\d+)
      total_debit: TOTAL DEBIT THIS MONTH\s*\(JUMLAH DEBIT\)\s*([\d,]+\.\d+)
      transaction: (\d{2}\/\d{2})\s+(\d{2}\/\d{2})\s+(.+?)\s+([\d,.]+(?:CR)?)\s*$
      statement_date: \d{2}\s(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\s\d{2}
      timezone: Asia/Kuala_Lumpur
      statement_format: "_2 Jan 06"
      date_format: "_2/1"
  TNG_WEB: