accounts:
# No account configurations - will use default statement type detection
statement:
  default_type: MAYBANK_CASA_AND_MAE
  MAYBANK_CASA_AND_MAE:
    patterns:
      starting_balance: BEGINNING BALANCE\s*([\d,]+\.\d+)
      ending_balance: ENDING BALANCE\s*:\s*([\d,]+\.\d+)
      credit_suffix: CR
      statement_date: (\d{2}\/\d{2}\/\d{2})
      statement_format: _2/01/06
      total_debit: TOTAL DEBIT\s*:\s*([\d,]+\.\d+)
      total_credit: TOTAL CREDIT\s*:\s*([\d,]+\.\d+)
      main_transaction_line: (\d{2}\/\d{2}(?:\/\d{2})?)(.+?)([\d,]*\.\d+[+-])\s([\d,]*\.\d+(DR)?)
      description_transaction_line: (^\s+\S.*)
      amount_debit_suffix: "-"
      balance_debit_suffix: DR
      date_format: "_2/01/06"
  MAYBANK_2_CC:
    patterns:
      credit_suffix: CR
      starting_balance: YOUR PREVIOUS STATEMENT BALANCE\s*([\d,]+\.\d+(?:CR)?)
      ending_balance: SUB TOTAL\/JUMLAH\s*([\d,]+\.\d+(?:CR)?)
      total_credit: TOTAL CREDIT THIS MONTH\s*\(JUMLAH KREDIT\)\s*([\d,]+\.\d+)
      total_debit: TOTAL DEBIT THIS MONTH\s*\(JUMLAH DEBIT\)\s*([\d,]+\.\d+)
      transaction: (\d{2}\/\d{2})\s+(\d{2}\/\d{2})\s+(.+?)\s+([\d,.]+(?:CR)?)\s*$
      statement_date: \d{2}\s(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\s\d{2}
      timezone: Asia/Kuala_Lumpur
      statement_format: "_2 Jan 06"
      date_format: "_2/1"
  TNG:
    patterns:
      transaction: '([A-Za-z''0-9: \&-]+?)\s+(\d{2}/\d{2}/\d{4})\s+(\d{2}:\d{2})\s+(.+?)\s+(.+?)\s+(.+?)\s+(.+?)\s+'
      transaction_date: 02/01/2006 15:04
      amount_numbers_pattern: ([+-]?)RM(\d+\.\d+)
      debit_suffix: "-"
